name: Probar Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Verifica codigo
      uses: actions/checkout@v3
    - name: Decir hola
      run: echo "¡Hola! El workflow está funcionando."
